### ISSUE TITLE
ARP resolution failing using virtio/low_end with vlan tags

### ISSUE THREAD

**Issue by AODtorusan** [cisco-system-traffic-generator/trex-core#292] opened 2019-06-25 08:05 UTC
I'm using trex in low-end mode with virtio interfaces, but I can't seem to get the L3 configuration ARP resolution to work when using vlans.

I'm setting up trex via the following pytjon script:

```
import sys
from time import sleep

sys.path.insert(0, "/usr/local/programs/trex-v2.57/" + "automation/trex_control_plane/interactive/")

from trex.stl.api import *

def act(client):
    client.acquire(ports = [0, 1])
    client.reset(ports = [0, 1])

    client.set_service_mode(ports = [0, 1], enabled=True)
    capture = client.start_capture(rx_ports = 0, limit = 100, mode = 'fixed')
    sleep(3)
    try:
        client.set_port_attr(ports=[0,1], promiscuous=True)
        pprint.pprint( client.get_port_info() )
        client.set_l3_mode(port=0, src_ipv4="172.18.120.254", dst_ipv4="172.18.120.1", vlan=811)
        #client.set_l3_mode(port=1, src_ipv4="10.2.2.254",     dst_ipv4="10.2.2.1",     vlan=812)
    except STLError as ex_error:
        print(ex_error)
    client.stop_capture(capture['id'], '/tmp/port_0_rx.pcap')
    client.set_service_mode(ports = [0, 1], enabled=False)

if __name__ == "__main__":
    client = STLClient( server="192.168.114.207")
    try:
        client.connect()
        act( client )
    finally:
        client.disconnect()
```

I get the following output

```
[{'arp': u'fa:16:3e:c0:68:30',
  u'cores': [0],
  u'description': u'Unknown',
  'dest': u'1.1.1.2',
  u'driver': u'net_af_packet',
  'fc': 'N/A',
  'fc_supported': 'no',
  'grat_arp': 'off',
  u'hw_mac': u'fa:16:3e:66:75:0b',
  u'index': 0,
  'ipv6': 'off',
  u'is_fc_supported': False,
  u'is_led_supported': False,
  u'is_link_supported': False,
  u'is_prom_supported': True,
  u'is_virtual': 'yes',
  u'is_vxlan_supported': 'no',
  'layer_mode': 'IPv4',
  'led_change_supported': 'no',
  'link': 'UP',
  'link_change_supported': 'no',
  'mult': 'off',
  u'numa': -1,
  u'pci_addr': u'N/A',
  'prom': 'on',
  'prom_supported': 'yes',
  u'rx': {u'caps': [u'flow_stats', u'latency', u'rx_bytes'],
          u'counters': 1023},
  'rx_filter_mode': 'fetch all',
  'rx_queue': 'off',
  'speed': 10.0,
  'src_ipv4': u'1.1.1.1',
  'src_mac': u'fa:16:3e:66:75:0b',
  'status': 'IDLE',
  u'supp_speeds': [],
  'vlan': '-',
  'vxlan_fs': '-'},
 {'arp': u'fa:16:3e:66:75:0b',
  u'cores': [0],
  u'description': u'Unknown',
  'dest': u'1.1.1.1',
  u'driver': u'net_af_packet',
  'fc': 'N/A',
  'fc_supported': 'no',
  'grat_arp': 'off',
  u'hw_mac': u'fa:16:3e:c0:68:30',
  u'index': 1,
  'ipv6': 'off',
  u'is_fc_supported': False,
  u'is_led_supported': False,
  u'is_link_supported': False,
  u'is_prom_supported': True,
  u'is_virtual': 'yes',
  u'is_vxlan_supported': 'no',
  'layer_mode': 'IPv4',
  'led_change_supported': 'no',
  'link': 'UP',
  'link_change_supported': 'no',
  'mult': 'off',
  u'numa': -1,
  u'pci_addr': u'N/A',
  'prom': 'on',
  'prom_supported': 'yes',
  u'rx': {u'caps': [u'flow_stats', u'latency', u'rx_bytes'],
          u'counters': 1023},
  'rx_filter_mode': 'fetch all',
  'rx_queue': 'off',
  'speed': 10.0,
  'src_ipv4': u'1.1.1.2',
  'src_mac': u'fa:16:3e:c0:68:30',
  'status': 'IDLE',
  u'supp_speeds': [],
  'vlan': '-',
  'vxlan_fs': '-'}]
Could not resolve following ports: [0]
```

As per #206 I set the ports in promiscuous mode, I start the trex server via "./t-rex-64 -i --iom 0 -v 7".  The output and /etc/trex_cfg.yaml config are in the attached file

I also simultaneously ran a normal tcpdump capture on port0 (eth1 in this case). When comparing the trex capture with the tcpdump capture, I did notice that the trex one had all the outer vlan tags removed.
Also in both captures I can see the arp reply from 98:5d:82:d9:12:b9 (but in the trex capture without vlan tag)

[trex.run.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/3324172/trex.run.txt)
[port_0_rx.pcap.gz](https://github.com/cisco-system-traffic-generator/trex-core/files/3324177/port_0_rx.pcap.gz)
[eth1.tcpdump.pcap.gz](https://github.com/cisco-system-traffic-generator/trex-core/files/3324178/eth1.tcpdump.pcap.gz)

**Comment by hhaim** [comment] 2019-06-25 08:26
This is a duplicate of #206. It is a DPDK driver issue

**Comment by AODtorusan** [comment] 2019-06-26 07:08
Since promiscuous mode does not fix it for me I thought it might be a different issue (it does seem to work when removing the low_end configuration property).

Thanks for the confirmation.

**Closed** 2019-06-27 13:25 UTC
