### ISSUE TITLE
trex-console default profile state 'STATE_UNKNOWN'

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#581] opened 2020-11-25 04:39 UTC
Hi, during the test by the trex-console, I found that the ASTF default profile is shown as "STATE_UNKNOWN" state.
![image](https://user-images.githubusercontent.com/4134762/100168110-f82c6b00-2f03-11eb-93b3-3b7905da1583.png)
@hhaim, is this your expected result?

**Comment by hhaim** [comment] 2020-11-25 08:17
@jsmoon no it is not expected

**Comment by bdollma** [comment] 2020-11-25 08:47
It should probably be STATE_IDLE.
https://trex-tgn.cisco.com/trex/doc/cp_astf_docs/api/client_code.html#trex.astf.trex_astf_client.ASTFClient.get_profiles_state

**Comment by jsmoon** [comment] 2021-02-23 08:26
@bdollma I think the following minor patch is needed to fix this issue.
```
--- a/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py
+++ b/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py
@@ -962,7 +962,7 @@ class ASTFClient(TRexClient):
         """
         states = {}
         for key, value in self.astf_profile_state.items():
-            states[key] = astf_states[value] if value else "STATE_UNKNOWN"
+            states[key] = astf_states[value] if value < len(astf_states) else "STATE_UNKNOWN"
         return states
 
     @client_api('getter', True)
```

**Comment by besdollma** [comment] 2021-02-24 16:06
Hi @jsmoon ,
I don't think this solves the problem. The state numbers are mapped to state names based on 
`astf_states = [
    'STATE_IDLE',
    'STATE_ASTF_LOADED',
    'STATE_ASTF_PARSE',
    'STATE_ASTF_BUILD',
    'STATE_TX',
    'STATE_ASTF_CLEANUP',
    'STATE_ASTF_DELETE']`
Meaning that if the state is 0 then we consider it idle, if it is 1 then it is loaded. 
We need to understand what the default profile state number is and why? 
I can see in the code that it is initialized at 0.
`        self.astf_profile_state = {'_': 0}
`
I will take a deeper look at this when I have some time.

**Comment by jsmoon** [comment] 2021-02-25 03:18
@besdollma
As far as I know, `astf_states` matched the state value. 0 value in T-Rex server means STATE_IDLE and it is the default value for the default profile '_'.
Furthermore, the `self.astf_profile_state = {'_': 0}` has no issue. It will be replaced by the `sync` result.
So, I think it is enough to resolve this issue.

**Comment by besdollma** [comment] 2021-03-04 12:12
@jsmoon 
Ok, I understand what you meant now.
The problem is that profile value = 0 evaluates as False. This returns state unknown even though the current value is found in the astf_states. 
Your solution will work, but to make it more generic (so we won't have these problems anymore) I suggest the following:

```
         states = {}
         for key, value in self.astf_profile_state.items():
-            states[key] = astf_states[value] if value else "STATE_UNKNOWN"
+            states[key] = astf_states[value] if value in range(len(astf_states)) else "STATE_UNKNOWN"
         return states
```
This will cover negative values as well.

**Comment by jsmoon** [comment] 2021-03-05 02:47
@bdollma looks good. I'll wait for your update.

**Comment by besdollma** [comment] 2021-03-05 07:46
@jsmoon 
I have fixed this in our internal repo. It will be part of the next release.

**Closed** 2021-03-15 00:25 UTC
